language: php

sudo: required

matrix:
  include:
    - php: 5.4
      env: DB=mysqli
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=postgres
    - php: 5.4
      env: DB=sqlite3
    - php: 5.5
      env: DB=mysqli
    - php: 5.6
      env: DB=mysqli
  fast_finish: true

env:
  global:
    - SNIFF="0"            # Should we run code sniffer on your code?
    - IMAGE_ICC="0"        # Should we run icc profile sniffer on your images?
    - PHPBB_BRANCH="3.1.x"

branches:
  only:
    - master
    - /^(3\.[1-9]|[4-9]\.\d)\.x$/

install:
  - travis/prepare-phpbb.sh $PHPBB_BRANCH
  - cd ../phpBB3
  - travis/setup-phpbb.sh $DB $TRAVIS_PHP_VERSION

script:
  - sh -c "if [ '$SNIFF' != '0' ]; then travis/ext-sniff.sh $DB $TRAVIS_PHP_VERSION $EXTSNIFF; fi"
  - sh -c "if [ '$IMAGE_ICC' != '0' ]; then travis/check-image-icc-profiles.sh $DB $TRAVIS_PHP_VERSION; fi"
  - phpBB/vendor/bin/phpunit --group conversion --bootstrap ./tests/bootstrap.php

